clear all
close all

%%Paramaters to define
MuTh=0.003;

%Files of Series

Series(1,1)=cellstr('Cyperus-Arganda2005');
Series(2,1)=cellstr('Cyperus-Arganda2006');
Series(3,1)=cellstr('Cyperus-Golega2006');
Series(4,1)=cellstr('Cyperus-Laroca2006');
Series(5,1)=cellstr('Cyperus-LarocaA2009');
Series(6,1)=cellstr('Cyperus-LarocaC2009');
Series(7,1)=cellstr('Cyperus-Miralcamp2010');
Series(8,1)=cellstr('Digi-Huelva 2008-1');
Series(9,1)=cellstr('Digi-Huelva2008-2');
Series(10,1)=cellstr('Digi-laroca2006');
Series(11,1)=cellstr('Digi-Miralcamp2010');
Series(12,1)=cellstr('Digi-Mollerusa2010');
Series(13,1)=cellstr('Echi-Laroca2006');
Series(14,1)=cellstr('Lolium-Albacete06-07');
Series(15,1)=cellstr('Lolium-Igualada06-07');
Series(16,1)=cellstr('Papaver-Elencin07-08');
Series(17,1)=cellstr('Papaver-Igualada06-07');
Series(18,1)=cellstr('Papaver-Murillo07-08');
Series(19,1)=cellstr('Polearacea-Huelva2-2008');
Series(20,1)=cellstr('Polaracea-Huelva2008');


% Globalresults=zeros(length(Series),8);

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Marc\Desktop\TFG\CitricosHuelva2008.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

%%% GENERAL...

Outputfolder = 'C:\Users\Marc\Desktop\TFG\';   %%% CARPETA ON TREBALLES


for w=1:length(Series)

%%%% PARTICULAR
% Auto-generated by MATLAB on 2015/10/21 13:38:52

%% Initialize variables.
    Infoseries =char(Series(w));
    filename = ([Outputfolder,Infoseries,'.txt']);
    delimiter = '\t';
    startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
    fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure ofdataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);
%  the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
    fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a fileand regenerate the
% script.

%% Allocate imported array to column variable names
    clear GHT Emerg LongTot LongF1 LongF3 Emergf GHTf Derivada Derivadaf EmergI LNEmergf Velocitatesp
    GHT = dataArray{:, 2};
    Emerg = dataArray{:, 1};

%% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;

LongTot=length(GHT);
LongF1=LongTot-2;
LongF2=LongF1-2;
LongF3=LongF2-2;
Emergf=zeros(LongF1,1);
GHTf=zeros(LongF2,1);
Derivada=zeros(LongF2,1);
Derivadaf=zeros(LongF3,1);
EmergI=zeros(LongF3,1);
LNEmergf=zeros(LongF3,1);
Velocitatesp=zeros(LongF3,1);

%%Primer filtre
    for i=1:LongF1
        Emergf(i)=((Emerg(i)*((GHT(i+2)-GHT(i+1))/(GHT(i+2)-GHT(i))))+Emerg(i+1)+(Emerg(i+2)*((GHT(i+1)-GHT(i))/(GHT(i+2)-GHT(i)))))/2;
    end

%mitja de GHT per les dades de la derivada i la Derivada
    for i=1:LongF2
        GHTf(i)=(GHT(i+3)+GHT(i+1))/2;
        Derivada(i)=(Emergf(i+2)-Emergf(i))/(GHT(i+3)-GHT(i+1));
    end


%%filtre de la derivada, interpolació de Emerg, Ln Emerg i Velocitat específica
    for i=1:LongF3
        Derivadaf(i)=(Derivada(i)*(GHTf(i+2)-GHTf(i+1))/(GHTf(i+2)-GHTf(i))+Derivada(i+1)+Derivada(i+2)*(GHTf(i+1)-GHTf(i))/(GHTf(i+2)-GHTf(i)))/2;
        EmergI(i)=Emergf(i+1)+(Emergf(i+3)-Emergf(i+1))*(GHTf(i+1)-GHT(i+2))/(GHT(i+4)-GHT(i+2));
        LNEmergf(i)=log(EmergI(i));
        Velocitatesp(i)=Derivadaf(i)/EmergI(i);
    end

    index=0;
    control=0;
    for i=1:LongF3
        if Velocitatesp(i)>MuTh && control==0
            index=index+1;
        else
            control=1; %% veure aquesta funcio
        end
    end
    
    if index >LongF3
        index=LongF3;
    end

        p = polyfit(LNEmergf, Velocitatesp,1);
        slope=p(1);
        ind=p(2);

% Fit model to data.
        [fitresult, gof] = fit( LNEmergf(:), Velocitatesp(:), 'poly1' );

% Plot fit with data.
        figure
        h = plot( fitresult, LNEmergf, Velocitatesp );
        legend( h, 'Velocitatesp vs. LNEmergf', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
        xlabel( 'LNEmergf' );
        ylabel( 'Velocitatesp' );
        grid on
  
%Variables ajustades

        Mu=-(slope);
        MuxK=ind;
        K=exp(MuxK/Mu);

%% Emerg Vs GHT gompertz
%proba de grafic

%% Fit: 'untitled fit 1'.
        [xData, yData] = prepareCurveData( GHT, Emerg );

% Set up fittype and options.
%         ft = fittype( '413.128*exp(-log(413.128/202)*exp(-0.0115*(x-d)))', 'independent', 'x', 'dependent', 'y' );
        ft = fittype( [K,'*exp(-log(',K,'/202)*exp(-',Mu,'*(x-d)))'], 'independent', 'x', 'dependent', 'y' );
        opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
        opts.Display = 'Off';
        opts.StartPoint = 176.62; %,,,%

% Fit model to data.
        [fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
        figure( 'Name', 'untitled fit 1' );
        h = plot( fitresult, xData, yData );
        legend( h, 'Emerg vs. GHT', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
        xlabel( 'GHT' );
        ylabel( 'Emerg' );
        grid on
        save figure


%obtenir el valor de Temperatua hidrotèrmica inicial Emergencia del valor
%en que Mullindar es més petita

        To=coeffvalues(fitresult);
        EmergI(index); %valor on supera mu treshold
        max(EmergI);
    
    
    
%%Excel
        Outputfolder = 'C:\Users\Marc\Desktop\TFG\';
        filename=([Outputfolder,'/Results',Infoseries,'.xlsx']);
        Titols1 = {'Serie','K','Mumax','GHTin','Mutreshold','Emergenciallindar','Emerg%','Control' };
        sheet = 1;
        xlRange = 'A1';
        xlswrite(filename,Titols1,sheet,xlRange)
 
        Titols2 = {'GHT','Emerg','GHTf','EmergI','LnEmerg','Velocitatesp'};
        sheet = 2;
        xlRange = 'A1';
        xlswrite(filename,Titols2,sheet,xlRange)

        Valors1 = [{Infoseries},K,Mu,To,MuTh,EmergI(index+1),(EmergI(index+1)/max(Emergf))*100,control];
        sheet = 1;
        xlRange = ['A2'];
        xlswrite(filename,Valors1,sheet,xlRange)
 
        Valors2 = [GHT,Emerg];
        Valors3 = [GHTf(2:LongF2-1),EmergI,LNEmergf,Velocitatesp];
        sheet = 2;
        xlRange = 'A2';
        xlswrite(filename,Valors2,sheet,xlRange)
        xlRange = 'C2';
        xlswrite(filename,Valors3,sheet,xlRange)

        Globalresults(w,1)=cellstr(Series(w));
        Globalresults(w,2:length(Valors1))=Valors1(2:length(Valors1));
end

